USE_CAMERA_STUB := true
#BOARD_VENDOR := meizu

# inherit from the proprietary version
-include vendor/Meizu/PRO5/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := m86

# Platform
TARGET_BOARD_PLATFORM := exynos5
TARGET_BOARD_PLATFORM_GPU := mali-t760mp8
TARGET_SLSI_VARIANT := cm
TARGET_SOC := exynos7420

# Flags
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=60  

# Architecture
TARGET_ARCH := arm64
TARGET_CPU_ABI := arm64-v8a
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_SMP := true

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_MKBOOTIMG_ARGS := --base 0x40078000 --kernel_offset 0x00008000 --ramdisk_offset 0x01f88000 --tags_offset 0xfff88100 --pagesize 4096
#BOARD_KERNEL_SEPARATED_DT := true


BOARD_BOOTIMAGE_PARTITION_SIZE := 25165824
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2684354560
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x130000000
BOARD_FLASH_BLOCK_SIZE := 131072

BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_23x41.h\"
TARGET_RECOVERY_INITRC := device/Meizu/PRO5/init.rc

# Sensors
TARGET_NO_SENSOR_PERMISSION_CHECK := true

# Kernel Configs

#TARGET_KERNEL_SOURCE := kernel/Meizu/PRO5
#TARGET_KERNEL_CONFIG := pro5_defconfig
#BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_CUSTOM_TOOLCHAIN := true
KERNEL_TOOLCHAIN := /home/absolu7e/cm13/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin
#KERNEL_TOOLCHAIN := /home/absolu7e/gcc-linaro-5.2-2015.11-x86_64_aarch64-linux-gnu/bin
KERNEL_TOOLCHAIN_PREFIX := aarch64-linux-android-

TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
#TARGET_USES_UNCOMPRESSED_KERNEL := true
#TARGET_KERNEL_SELINUX_CONFIG := 
#TARGET_KERNEL_VARIANT_CONFIG :=
#VARIANT_CONFIG :=
#TIMA_DEFCONFIG :=
TARGET_PREBUILT_KERNEL := device/Meizu/PRO5/kernel

BOARD_NEEDS_LZMA_MINIGZIP := true

# Recovery:Start

# Use this flag if the board has a ext4 partition larger than 2gb
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SUPPRESS_SECURE_ERASE := true

# Recovery
TARGET_OTA_ASSERT_DEVICE := PRO5,m86
RECOVERY_GRAPHICS_FORCE_USE_LINELENGTH := true
RECOVERY_FSTAB_VERSION := 2
TARGET_BOOTANIMATION_SIZE := 1920x1080

# TWRP specific build flags
TW_THEME := portrait_hdpi
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_REAL_SDCARD := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_HAS_NO_BOOT_PARTITION := true
TW_HAS_NO_RECOVERY_PARTITION := true
TW_NO_EXFAT_FUSE := true
TW_NO_EXFAT := true

TW_ALWAYS_RMRF := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
#TW_MAX_BRIGHTNESS := 255
BOARD_USES_MMCUTILS := true
BOARD_HAS_NO_MISC_PARTITION := true
RECOVERY_USE_MIGRATED_STORAGE := true
TW_NO_REBOOT_BOOTLOADER := true
TW_HAS_DOWNLOAD_MODE := true
#TW_MTP_DEVICE := /dev/usb_mtp_gadget
#TW_INCLUDE_CRYPTO := true
TW_EXCLUDE_SUPERSU := true
TARGET_RECOVERY_PIXEL_FORMAT := "ABGR_8888"

#TARGET_USES_64_BIT_BINDER := true
#TARGET_CPU_SMP := true
#ARCH_ARM_HAVE_TLS_REGISTER := true

# Compaction
#ART_USE_HSPACE_COMPACTION := true

# HWComposer
BOARD_USES_HWC_SERVICES := true
BOARD_USES_HWCOMPOSER := true

# NFC
BOARD_NFC_HAL_SUFFIX := universal7420

# OpenGL
USE_OPENGL_RENDERER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3

# FIMG2D
BOARD_USES_SKIA_FIMGAPI := true

# (G)SCALER
BOARD_USES_SCALER := true
BOARD_USES_DT := true

### FONTS
EXTENDED_FONT_FOOTPRINT := true

# Samsung OpenMAX Video
BOARD_USE_STOREMETADATA := true
BOARD_USE_METADATABUFFERTYPE := true
BOARD_USE_DMA_BUF := true
BOARD_USE_ANB_OUTBUF_SHARE := true
BOARD_USE_IMPROVED_BUFFER := true

# Renderscript
#BOARD_OVERRIDE_RS_CPU_VARIANT_32 := cortex-a15
BOARD_OVERRIDE_RS_CPU_VARIANT_64 := cortex-a57

# Exynos display
BOARD_USES_VIRTUAL_DISPLAY := true

BOARD_HAS_NO_SELECT_BUTTON := true

#BOARD_CUSTOM_GRAPHICS := /home/absolu7e/cm13/device/Meizu/PRO5/recovery/graphics.c
